version: '3.8'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      #MONTAR EL ARCHIVO wordpress.sql COMO BD
      - ./git-clone/wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql
      #PARA PERSISTENCIA EN LA BBDD
      - db_data:/var/lib/mysql
    environment:
      #VARIABLES DE ENTORNO CREDENCIALES ACCESO A BBDD.
      #EL SERVIDOR DE MYSQL UTILIZARÁ ESTAS VARIABLES; CREARÁ TAMBIÉN EL USUARIO "user"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress

  # Wordpress
  nginx:
    depends_on:
      - php
    #image: nginx:latest
    #ports:
    #  - '80:80'
    build:
      #SE USA UN DOCKERFILE PARA PODER AUTOMARIZAR EL COMANDO chown Y CAMBIAR USUARIO DE LA CARPETA /var/www/wordpress A www-data
      dockerfile: ./nginx/dockerfile
    restart: always
    volumes:
      #PARA COGER TODA LA INFORMACION DE WORDPRESS Y MOVERLO A /var/www/wordpress
      - ./git-clone:/var/www/wordpress
      #PARA SUSTITUIR EL FICHERO DE CONFIGURACIÓN POR EL NUESTRO MODIFICADO
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #USER 0=root; PARA QUE PUEDA EJECUTAR EL COMANDO chown SIN CAGARSE
    user: "0:0"
    networks:
      - wordpress
  php:
    depends_on:
      - db
    build: 
      dockerfile: ./php/dockerfile
    volumes:
      #PHP NECESITA TAMBIÉN ACCEDER A LOS FICHEROS DE WORDPRESS PORQUE ES EL QUE SE ENCARGA DE COMPILAR SU CODIGO
      - ./git-clone:/var/www/wordpress
    environment:
      #PHP NECESITA ACCEDER A LA BD PARA PODER VER EL CONTENIDO DE PÁGINAS, POST, PLUGGINS, ETC
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress

  varnish:
    depends_on:
      - nginx
    image: varnish:latest
    ports:
      #ES EL QUE RECIBE LAS PETICIONES WEB
      - 80:80
    restart: always
    user: root
    volumes:
      #CONFIGURACION DE VARNISH MODIFICADA; DONDE REDIRIGE HACIA LA NGINX
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    tmpfs:
      #DIRECTORIO DONDE SE ALMACENARA LA INFORMACION CACHEADA
      - /var/lib/varnish:exec
    environment:
      #CANTIDAD DE MEMORIA PARA ALMACENAR LA INFORMACION CACHEADA
      - VARNISH_SIZE=2G
    #300 ES EL TIEMPO MÁXIMO QUE PARA GUARDAR LA INFORMACION EN CACHE
    command: "-p default_keep=300"

    networks:
      - wordpress

  redis:
    depends_on:
      - db
    image: redis:latest
    restart: always
    networks:
      - wordpress


networks:
  wordpress:
volumes:
  db_data:
