FROM ubuntu:20.04

# BLOCK : Make PHP works
RUN apt-get update
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:ondrej/php
# FIN BLOCK

RUN apt-get -y update && apt-get install -y \
    php7.4 \
    php7.4-fpm \
    php7.4-mysql \
    php7.4-json \
    php7.4-curl \
    php7.4-sqlite3 \
    php7.4-xml \
    php7.4-bcmath \
    php7.4-zip \
    php7.4-mbstring \
    php-xdebug \
    php-ast

WORKDIR /var/www/wordpress

CMD ["php-fpm"]
#CMD ["/etc/init.d/php7.4-fpm start -F"]

EXPOSE 9000
